export enum UserActionTypes {
  LOGIN_START = "login_start",
  LOGIN_SUCCESS = "login_success",
  LOGIN_FAILURE = "login_failure",
  SIGNUP_START = "signup_start",
  SIGNUP_SUCCESS = "signup_success",
  SIGNUP_FAILURE = "signup_failure",
  LOGOUT_START = "logout_start",
  LOGOUT_SUCCESS = "logout_success",
  LOGOUT_FAILURE = "logout_failure",
  UPDATE_USER_START = "update_user_start",
  UPDATE_USER_SUCCESS = "update_user_success",
  UPDATE_USER_PASSWORD_START = "update_user_password_start",
  UPDATE_USER_PASSWORD_SUCCESS = "update_user_password_success",
  UPDATE_USER_PASSWORD_FAILURE = "update_user_password_failure",
  REMOVE_MESSAGE = "remove_message",
}
